### ISSUE TITLE
Wrong directory for vcfs

### ISSUE THREAD

**Issue by hyanwong** [deboraycb/ARGsims#2]
According to `tsinferdate/2_tsinfer_date.py` I run

```
python3 ./2_tsinfer_date.py std 8 2e-8 > tsinfer_date_std.out2
```

But this seems to be losing for VCFs in `../vcf/sim_std_0.vcf`, whereas I guess it should look for them in `../../vcf/sim_std_0.vcf`?

**Comment by hyanwong** [comment]
Also the existing vcfs are .gz compressed, so I guess should be read from e.g. `../../vcf/sim_std_0.vcf.gz`?

Is there any reason why you don't just read the msprime simulations directly into a tsinfer sample data file using `tsinfer.SampleData.from_tree_sequence("../../trees/my_simulated_ts.trees")`?

**Comment by deboraycb** [comment]
Thanks for pointing out the wrong path, Yan!
I chose to use the VCF as a starting point for all methods that I compared in the paper just to treat them all as equally as possible. But I guess for simulations with tsinfer/tsdate only it would make more sense to read the msprime simulations directly like you say.
